import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
// import Header from '@/components/header/header'
import Footer from '@/components/footer/footer'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       
      <body className={inter.className}>{children}</body>
      <Footer/>
    </html>
  )
}
